env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - implicit-dependencies
rules:
  implicit-dependencies/no-implicit:
    - error
    - dev: true
      peer: true
      optional: false
settings:
  react:
    version: 18.0.0
