# For docs, see
# https://github.com/prettier/prettier/blob/master/README.md#configuration-file

printWidth: 80
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
